name: PR Syntax Check

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    concurrency: pr-title-check
    steps:
      - name: Check PR Title Format
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "Checking PR Title: $PR_TITLE"
          if [[ ! "$PR_TITLE" =~ ^(feat:|fix:|fix!:|feat!:|refactor!:) ]]; then
            echo "❌ PR title must start with feat:, fix:, fix!:, feat!:, or refactor!:"
            exit 1
          fi
          echo "✅ PR title format is valid."